# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160417_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.URLField(blank=True, default='', verbose_name='封面'),
        ),
    ]
