# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160627_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='书名')),
                ('url', models.URLField(default='', verbose_name='链接')),
            ],
            options={
                'verbose_name_plural': '推荐阅读',
                'verbose_name': '推荐阅读',
            },
        ),
    ]
